### ISSUE TITLE
"cat" errors on first run

### ISSUE THREAD

**Issue by crmaykish** [xcjs/blur-monitor#23]
(node:12920) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Command "cat" failed. Please check for earlier errors.
(node:12920) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12920) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)

Got this error and then a string of promise rejections on app startup.

Clean install on a brand new Debian system.

**Comment by xcjs** [comment]
This looks like an issue with me calling cat on /etc/lsb-release myself instead of using the lsb_release command. I'll make the change as soon as possible.

**Comment by xcjs** [comment]
@crmaykish This has been resolved in the latest [development](https://github.com/xcjs/blur-monitor/tree/development) branch.
