### ISSUE TITLE
error on mac

### ISSUE THREAD

**Issue by jackieelong** [xcjs/blur-monitor#24]
gulp build

Error: ELOOP: too many symbolic links encountered, open '/blur-monitor/src/assets/img/app/apps/thunar.svg'

**Comment by xcjs** [comment]
Sounds like I've used too many symlinks for certain platforms. It may be best to replace them with copies of the files instead.

The only place this is used is in the application icons. This should be an easy enough fix.

**Comment by xcjs** [comment]
@codepython What does cat show when you run cat /blur-monitor/src/assets/img/app/apps/thunar.svg ?

I'd prefer not to get rid of the symlinks if possible. Perhaps one of the symlinks has an invalid reference?

**Comment by xcjs** [comment]
I need someone with access to a Mac and more knowledge of this particular issue.

**Comment by xcjs** [comment]
@codepython Are you able to assist with figuring out what the cause of this issue is? I'd like to resolve it but lack the equipment to do so.
