### ISSUE TITLE
Default Username and Password

### ISSUE THREAD

**Issue by csmith1568** [xcjs/blur-monitor#26]
Hi guys,

I'm just trying to log into the system and i'm not having much luck.

I've searched for the information in the files and tried:
vm.username : vm.password
and
n.username : n.password

Does anybody know?

Sorry if i've been blind. but i cant seem to find it written in the docs.

Thanks all for a great system though

**Comment by xcjs** [comment]
@csmith1568 

The credentials are the same ones used for the account running the server.

For example, if your credentials you use to login to the server and run the server are:

csmith1568
hunter2

...those are the ones you would use to access your system information.

**Comment by xcjs** [comment]
@csmith1568 Can you confirm if you are still having issues? I will close this issue if I receive no response.
